apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-control
  labels:
    app: panel-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-control
  template:
    metadata:
      labels:
        app: panel-control
    spec:
      containers:
      - name: panel-control
        image: panel-control:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: panel-control-service
spec:
  selector:
    app: panel-control
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer